---
title: "Rworksheet.lauron#2.Rmd"
author: "Mary Ghale C. Lauron"
date: "2025-09-29"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```
#1a operator vector
operator <- -5,5
#output
#[1] -5 -4 -3 -2 -1  0  1  2  3  4  5 - the output start -5 to 5
#1b
x <-1:7
x
#output 
#[1] 1 2 3 4 5 6 7

#2 seq() function
seq(1,3, by=0.2)
#output
[1] 1.0 1.2 1.4 1.6 1.8 2.0 2.2 2.4 2.6 2.8 3.0 - the values added by 0.2 until it reach 3.0

#3
age<-c(34, 28, 22, 36, 27, 18, 52, 39, 42, 29, 35, 31, 27,
22, 37, 34, 19, 20, 57, 49, 50, 37, 46, 25, 17, 37, 43, 53, 41, 51, 35,
24,33, 41, 53, 40, 18, 44, 38, 41, 48, 27, 39, 19, 30, 61, 54, 58, 26,
18)
#3a
age[3]
#output
[1] 22
#3b
age[c(2,4)]
#output
[1] 28 36
#3c
age[-1]
#output
 [1] 28 22 36 27 18 52 39 42 29 35 31 27 22 37 34 19 20 57 49 50 37 46 25 17 37 43 53 41 51 35 24 33 41 53 40 18
[37] 44 38 41 48 27 39 19 30 61 54 58 26 18

#4
names(x) <- c("first"=3, "second"=0, "third"=9)
names(x)
#ouput
[1] "3" "0" "9" NA  NA  NA  NA 
names(x)[c("first", "third")]
#output
[1] NA NA - the first and third values are NA NA

#5
x <- -3:2
#output
[1] -3 -2 -1 0 1 2 
x[2] <- 0
x
#output
[1] -3  0 -1  0  1  2

#6
month <- c("Jan", "Feb", "March", "Apr", "May", "June")
price_per_liter <- c(52.50, 57.25, 60.00, 65.00, 74.25, 54.00)
purchase_quantity <- c(25, 30, 40, 50, 10, 45)

# Create data frame
diesel <- data.frame(month, price_per_liter, purchase_quantity)

# Print data frame
print(diesel)
#output
month price_per_liter purchase_quantity
1   Jan           52.50                25
2   Feb           57.25                30
3 March           60.00                40
4   Apr           65.00                50
5   May           74.25                10
6  June           54.00                45

#6b avg_expenditure from jan to june
avg_expenditure <- weighted.mean(price_per_liter, purchase_quantity)

# Print result
print(avg_expenditure)
#output
[1] 59.2625

#7
data <- c(length(rivers), sum(rivers), mean(rivers), median(rivers), var(rivers),
sd(rivers), min(rivers), max(rivers))
data
#output
[1]    141.0000  83357.0000    591.1844    425.0000 243908.4086    493.8708
[7]    135.0000   3710.0000

#8 vector
power_ranking <- c(1,2,3,4,5,6,7,8,9,10,
                   11,12,13,14,15,16,17,18,19,20,
                   21,22,23,24,25)

celebrity_name <- c("Tom Cruise","Rolling Stones","Oprah Winfrey","U2",
                    "Tiger Woods","Steven Spielberg","Howard Stern",
                    "50 Cent","Cast of the Sopranos","Dan Brown",
                    "Bruce Springsteen","Donald Trump","Muhammad Ali",
                    "Paul McCartney","George Lucas","Elton John",
                    "David Letterman","Phil Mickelson","J.K. Rowling",
                    "Brad Pitt","Peter Jackson","Dr. Phil McGraw",
                    "Jay Lenon","Celine Dion","Kobe Bryant")

pay <- c(67,90,225,110,90,332,302,41,52,88,
         55,44,55,40,233,34,40,47,75,25,
         39,45,32,40,31)
celebs <- data.frame(power_ranking, celebrity_name, pay)
print(celebs)

# Modify J.K. Rowling's power ranking and pay
celebs[celebs$celebrity_name == "J.K. Rowling", "power_ranking"] <- 15
celebs[celebs$celebrity_name == "J.K. Rowling", "pay"] <- 90
# Print updated table
print(celebs)
#output
power_ranking       celebrity_name pay
1              1           Tom Cruise  67
2              2       Rolling Stones  90
3              3        Oprah Winfrey 225
4              4                   U2 110
5              5          Tiger Woods  90
6              6     Steven Spielberg 332
7              7         Howard Stern 302
8              8              50 Cent  41
9              9 Cast of the Sopranos  52
10            10            Dan Brown  88
11            11    Bruce Springsteen  55
12            12         Donald Trump  44
13            13         Muhammad Ali  55
14            14       Paul McCartney  40
15            15         George Lucas 233
16            16          Elton John  34
17            17      David Letterman  40
18            18       Phil Mickelson  47
19            15         J.K. Rowling  90
20            20            Brad Pitt  25
21            21        Peter Jackson  39
22            22      Dr. Phil McGraw  45
23            23            Jay Lenon  32
24            24          Celine Dion  40
25            25          Kobe Bryant  31
 

#8c Interpret the data
The data is about celebrities ranked according to power. Their ranking seems to depend more on popularity and demand rather than just their pay, since some celebrities have a higher rank despite earning less than others. This suggests that pay alone does not determine influence. However, the reliability of the pay figures is uncertain because it is not clearly stated whether the amounts are in millions or billions.
